### ISSUE TITLE
Clean up tracking of interface pairs in contact

### ISSUE THREAD

**Issue by ebchin** [LLNL/Tribol#31]
Look into simplifying how interface pairs are stored and whether or not they are in contact.

**Comment by srwopschall** [comment]
@ebchin - I think this has been modified to some extent where each pair is designated as a contact candidate, rather than in contact or not in contact. A pair may exist as an interface pair, but may not be a contact candidate, and so it doesn't make sense to store "in contact" logic at the interface pair level. A pair that is a contact candidate after the filters will have a contact plane associated with it. The contact plane is where "in contact" is stored, if it make sense. For common-plane, this makes sense because you need the contact plane to compute the single integration point gap (centroidal gap), and so the contact plane object can hold the gap, and also whether it is "in contact" or not. For mortar it is more complicated since the gap is a nodal function, and just because a face node is not in contact doesn't mean that the face is not in contact. In this way, the contact plane's logic of "in-contact" or not doesn't really apply; however, the interface pair "contact candidate" logic still holds. In-contact logic for mortar really means querying the nodal gap function.

Anyway, these designations have been updated in a prior PR reconciling interface pairs that may or may not be a contact candidate with the number of contact planes that exist only for contact candidates. I think for now this issue can be closed? Thoughts?

**Comment by ebchin** [comment]
I agree, the updated variable naming helps clean things up.  Let's close this.
